In [1]:
import numpy as np
import tensorflow as tf
import scipy.io as io

label_dict = {
    'N':0,
    'A':1,
    'O':2,
    '~':3
}

data = []
label = []
lens = []

annotations = open('./training2017/REFERENCE.csv', 'r').read().splitlines()
for line in annotations:
    fname, label_str = line.split(',')
    
    x = io.loadmat('./training2017/'+fname+'.mat')['val'].squeeze()
    data.append(x)
    
    y = label_dict[label_str]
    label.append(y)
    
    lens.append(len(x))
    
assert(len(label) == len(data) == len(lens))
data_size = len(data)

# No problem with different lengths
# Using np.array because slice indexing does not copy the data
# While native python slicing does
data = np.array(data)
label = np.array(label)
lens = np.array(lens)

In [2]:
#a = list(range(10))
a = np.arange(10)
b = a[3:5]
b[0] = 10
a

array([ 0,  1,  2, 10,  4,  5,  6,  7,  8,  9])

In [11]:
def shuffle():
    global data
    global label
    global lens
    p = np.random.permutation(data_size)
    # Using fancy indexing for Unison Shuffle
    data = data[p]
    label = label[p]
    lens = lens[p]
    

def batch_pool(batch_size=4, num_epochs=10, random=True):
    n = batch_size
    if random:
        shuffle()
    for _ in range(num_epochs):
        for i in range(0, data_size, batch_size):
            yield data[i:i+n], label[i:i+n], lens[i:i+n]

In [13]:
batch_feeder = batch_pool()
list(batch_feeder)

[(array([array([301, 325, 342, ..., 119,  66,  14], dtype=int16),
         array([1427, 1641, 1853, ...,  -22,  -15,   -8], dtype=int16),
         array([202, 249, 307, ..., 289, 284, 207], dtype=int16),
         array([ 73,  96, 123, ..., -97, -62, -40], dtype=int16)], dtype=object),
  array([0, 2, 2, 0]),
  array([ 9000, 18000,  9000,  9000])),
 (array([array([227, 270, 323, ...,  -4,  -8, -10], dtype=int16),
         array([ 18,  20,  28, ..., -38, -36, -34], dtype=int16),
         array([38, 53, 64, ..., 42, 39, 36], dtype=int16),
         array([ 10,  12,  13, ..., -21, -17, -13], dtype=int16)], dtype=object),
  array([0, 0, 0, 1]),
  array([9000, 9000, 4272, 9000])),
 (array([array([-111, -134, -150, ...,  -35,  -28,  -16], dtype=int16),
         array([260, 302, 352, ..., -33, -30, -27], dtype=int16),
         array([  -85,  -108,  -144, ..., -1190,  -961,  -751], dtype=int16),
         array([-273, -327, -384, ...,  -60,  -46,  -31], dtype=int16)], dtype=object),
  array([0, 0,