In [149]:
import numpy as np
annot_lines = open('./raw/REFERENCE.csv', 'r').read().splitlines()
np.random.shuffle(annot_lines)
annot_dict = {s:s.split(',')[1] for s in annot_lines}

In [150]:
index_dict = {
        'N':[],
        'A':[],
        'O':[],
        '~':[]
}
for idx, line in enumerate(annot_lines):
    index_dict[annot_dict[line]].append(idx)
    

In [151]:
list(map(lambda x: print(x[0], len(x[1])), index_dict.items()))

~ 46
A 771
N 5154
O 2557


[None, None, None, None]

# Data separation
* Train 80% 
* Validation 10%
* Test 10%

In [152]:
TRAIN_P = .8
VAL_P = .1
TEST_P = .1

train_reference = open('raw/TRAIN.csv', 'w')
validation_reference = open('raw/VALIDATION.csv', 'w')
test_reference = open('raw/TEST.csv', 'w')

for idxs in index_dict.values():
    l = len(idxs)
    train_reference.writelines(
        '%s\n'%annot_lines[i] for i in idxs[:int(l*TRAIN_P)])
    validation_reference.writelines(
        '%s\n'%annot_lines[i] for i in idxs[int(l*TRAIN_P):int(l*(TRAIN_P+VAL_P))])
    test_reference.writelines(
        '%s\n'%annot_lines[i] for i in idxs[int(l*(TRAIN_P+VAL_P)):])
        

In [153]:
['%s\n'%annot_lines[i] for i in idxs[:int(l*TRAIN_P)]][-10:]

['A05056,O\n',
 'A01635,O\n',
 'A04130,O\n',
 'A04384,O\n',
 'A03970,O\n',
 'A07348,O\n',
 'A03015,O\n',
 'A06826,O\n',
 'A02696,O\n',
 'A07018,O\n']

# Validation of the separation

In [154]:
def get_counts(fname):
    annot_lines = open(fname, 'r').read().splitlines()
    np.random.shuffle(annot_lines)
    annot_dict = {s:s.split(',')[1] for s in annot_lines}

    index_dict = {
            'N':[],
            'A':[],
            'O':[],
            '~':[]
    }
    for idx, line in enumerate(annot_lines):
        index_dict[annot_dict[line]].append(idx)    

    print(fname)
    for label, idx in index_dict.items():
        print(label, len(idx))
    print('\n')
    
    return np.array([len(idx) for idx in index_dict.values()])

In [155]:
orig_count = get_counts('raw/REFERENCE.csv')
train_count = get_counts('raw/TRAIN.csv')
valid_count = get_counts('raw/VALIDATION.csv')
test_count = get_counts('raw/TEST.csv')

print(np.round(orig_count*TRAIN_P) - train_count)
print(np.round(orig_count*VAL_P) - valid_count)
print(np.round(orig_count*TEST_P) - test_count)

raw/REFERENCE.csv
~ 46
A 771
N 5154
O 2557


raw/TRAIN.csv
~ 36
A 616
N 4123
O 2045


raw/VALIDATION.csv
~ 5
A 77
N 515
O 256


raw/TEST.csv
~ 5
A 78
N 516
O 256


[ 1.  1.  0.  1.]
[ 0.  0.  0.  0.]
[ 0. -1. -1.  0.]


In [159]:
noise = open('raw/NOISE_CLASS_REF.csv', 'w')
atrium = open('raw/ATRIUM_CLASS_REF.csv', 'w')
normal = open('raw/NORMAL_CLASS_REF.csv', 'w')
other = open('raw/OTHER_CLASS_REF.csv', 'w')

noise.writelines('%s\n'%annot_lines[i] for i in index_dict['~'])
atrium.writelines('%s\n'%annot_lines[i] for i in index_dict['A'])
normal.writelines('%s\n'%annot_lines[i] for i in index_dict['N'])
other.writelines('%s\n'%annot_lines[i] for i in index_dict['O'])

In [161]:
type('a') == str

True

In [ ]:
tf.